// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataStoreP2P.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DataStore.P2P.GrpcGen {
  /// <summary>
  /// Service definition.
  /// </summary>
  public static partial class P2PGrpc
  {
    static readonly string __ServiceName = "DataStore.P2P.P2PGrpc";

    static readonly grpc::Marshaller<global::DataStore.P2P.GrpcGen.Request> __Marshaller_DataStore_P2P_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataStore.P2P.GrpcGen.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DataStore.P2P.GrpcGen.Reply> __Marshaller_DataStore_P2P_Reply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataStore.P2P.GrpcGen.Reply.Parser.ParseFrom);

    static readonly grpc::Method<global::DataStore.P2P.GrpcGen.Request, global::DataStore.P2P.GrpcGen.Reply> __Method_Send = new grpc::Method<global::DataStore.P2P.GrpcGen.Request, global::DataStore.P2P.GrpcGen.Reply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Send",
        __Marshaller_DataStore_P2P_Request,
        __Marshaller_DataStore_P2P_Reply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DataStore.P2P.GrpcGen.DataStoreP2PReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of P2PGrpc</summary>
    public abstract partial class P2PGrpcBase
    {
      public virtual global::System.Threading.Tasks.Task<global::DataStore.P2P.GrpcGen.Reply> Send(global::DataStore.P2P.GrpcGen.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for P2PGrpc</summary>
    public partial class P2PGrpcClient : grpc::ClientBase<P2PGrpcClient>
    {
      /// <summary>Creates a new client for P2PGrpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public P2PGrpcClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for P2PGrpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public P2PGrpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected P2PGrpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected P2PGrpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::DataStore.P2P.GrpcGen.Reply Send(global::DataStore.P2P.GrpcGen.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Send(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DataStore.P2P.GrpcGen.Reply Send(global::DataStore.P2P.GrpcGen.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Send, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DataStore.P2P.GrpcGen.Reply> SendAsync(global::DataStore.P2P.GrpcGen.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DataStore.P2P.GrpcGen.Reply> SendAsync(global::DataStore.P2P.GrpcGen.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Send, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override P2PGrpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new P2PGrpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(P2PGrpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Send, serviceImpl.Send).Build();
    }

  }
}
#endregion
